version: '3.7'
services:

  #nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - "443:443"
    restart: always
    # depends_on:
    #   - wordpress
    networks:
      - docker-network

  # wordpress
  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context: ./wordpress
  #     dockerfile: wordpress.dockerfile
  #   restart: always
  #   networks:
  #     - docker-network
  #   volumes:
  #     - wordpress_data:/var/www/html

    # depends_on:
    #   - mariadb
    #   - redis
    # ports:
    #  - "??:??"
    # environment:
    #   WORDPRESS_DB_HOST: mariadb
    #   WORDPRESS_DB_USER: root
    #   WORDPRESS_DB_PASSWORD: root
    #   WORDPRESS_DB_NAME: wordpress

    # mariaDB
  # mariadb:
  #   container_name: mariadb
  #   build:
  #     context: ./mariadb
  #     dockerfile: mariadb.dockerfile
  #   networks:
  #     - docker-network
  #   volumes:
  #     - db_data:/var/lib/mysql

volumes:
  # db_data
  # wordpress_data:

networks:
  docker-network: