services:

  #nginx
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "443:443"
    restart: always
    # networks:
    #   - docker-network

  # mariaDB
  # mariadb:
  #   container_name: mariadb
  #   build:
  #     context: ./mariadb
  #     dockerfile: mariadb.dockerfile
  #   networks:
  #     - docker-network
  #   volumes:
  #     - db_data:/var/lib/mysql

  # wordpress

# volumes:
#   # db_data
  # wordpress_data

# networks:
#   # docker-network